# Uncomment the next line to define a global platform for your project
use_frameworks!
platform :ios, '9.0'

target 'SearchUserMVP' do
  pod 'Alamofire', '~> 4.5'
  pod 'AlamofireObjectMapper', '~> 4.1.0'
  pod 'SwiftLint'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            # these libs work now only with Swift3.2 in Xcode9
            if ['ObjectMapper'].include? target.name
                configuration.build_settings['SWIFT_VERSION'] = "3.2"
            end
        end
    end
end